INSERT INTO recipes (name, description, image, serving_size, directions, tags, created_at) 
VALUES 
  ('Spaghetti Bolognese', 'Classic Italian pasta dish', 'https://via.placeholder.com/150?text=Spaghetti+Bolognese', 4, 'Boil spaghetti and prepare Bolognese sauce.', '{"Dairy-Free", "Gluten-Free", "Keto" , "Paleo", "< 15 minutes"}', '2024-02-05 12:30:00'),
  ('Chicken Alfredo', 'Creamy Alfredo pasta with grilled chicken', 'https://via.placeholder.com/150?text=Chicken+Alfredo', 3, 'Cook chicken and toss with Alfredo sauce and pasta.', '{"Vegetarian", "Vegan", "Dairy-Free", "Gluten-Free", "Keto" , "Paleo", "15 - 30 minutes"}','2024-02-05 13:15:00'),
  ('Vegetarian Stir-Fry', 'Colorful vegetable stir-fry', 'https://via.placeholder.com/150?text=Vegetarian+Stir-Fry', 2, 'Stir-fry assorted veggies with soy sauce and spices.', '{"Vegetarian", "Vegan", "Dairy-Free", "Gluten-Free", "Keto" , "Paleo", "30 - 45 minutes"}','2024-02-05 14:00:00'),
  ('Grilled Salmon', 'Healthy grilled salmon fillet', 'https://via.placeholder.com/150?text=Grilled+Salmon', 2, 'Marinate salmon and grill until cooked.', '{"Vegetarian", "Vegan", "Dairy-Free", "Gluten-Free", "Keto" , "Paleo","1 - 2 hours"}','2024-02-05 14:45:00'),
  ('Mushroom Risotto', 'Creamy Italian risotto with mushrooms', 'https://via.placeholder.com/150?text=Mushroom+Risotto', 4, 'Sauté mushrooms and cook with Arborio rice in broth.', '{"Dairy-Free", "Gluten-Free", "Keto" , "Paleo","> 2 hours"}','2024-02-05 15:30:00'),
  ('Vegan Chili', 'Spicy and hearty vegan chili', 'https://via.placeholder.com/150?text=Vegan+Chili', 6, 'Combine beans, vegetables, and spices in a pot and simmer.', '{"Vegetarian", "Vegan", "Dairy-Free", "Gluten-Free", "Keto" , "Paleo","1 - 2 hours"}','2024-02-05 16:15:00'),
  ('Homemade Pizza', 'Classic homemade pizza with various toppings', 'https://via.placeholder.com/150?text=Homemade+Pizza', 8, 'Prepare pizza dough, add toppings, and bake.', '{"Gluten-Free", "Keto" , "Paleo","1 - 2 hours"}','2024-02-05 17:00:00'),
  ('Lemon Garlic Shrimp', 'Lemon-infused garlic shrimp', 'https://via.placeholder.com/150?text=Lemon+Garlic+Shrimp', 3, 'Sauté shrimp with garlic and lemon juice until golden brown.', '{"Dairy-Free", "Gluten-Free", "Keto" , "Paleo","1 - 2 hours"}','2024-02-05 17:45:00'),
  ('Caprese Salad', 'Refreshing Caprese salad with tomatoes and mozzarella', 'https://via.placeholder.com/150?text=Caprese+Salad', 2, 'Layer tomatoes, mozzarella, and basil. Drizzle with balsamic glaze.', '{"Vegetarian", "Vegan", "Dairy-Free", "Gluten-Free", "Keto" , "Paleo","> 2 hours"}','2024-02-05 18:30:00'),
  ('Chocolate Cake', 'Decadent chocolate cake with fudge frosting', 'https://via.placeholder.com/150?text=Chocolate+Cake', 10, 'Bake chocolate cake and frost with fudge icing.', '{"Vegetarian", "Vegan", "Dairy-Free", "Gluten-Free", "Keto" , "Paleo","> 2 hours"}','2024-02-05 19:15:00');